name: Label opened prs

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  move_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Move to the PR-WIP column
      uses: alex-page/github-project-automation-plus@v0.7.1
      with:
        project: LiSA
        column: PR-WIP
        repo-token: ${{ secrets.SSVPAT }}
    - name: add label
      uses: andymckay/labeler@22d5392de2b725cea4b284df5824125054049d84
      with:
        add-labels: 'work in progress'
        repo-token: ${{ secrets.SSVPAT }}